REM Run this on target DB as SYS

create user cis$$rtpa$$ identified by cis$$rtpa$$;
grant create session to cis$$rtpa$$;
grant create session,create type, create table,create procedure, create synonym to cis$$rtpa$$;
grant select on sys.v_$parameter to cis$$rtpa$$;
grant select on sys.v_$database to cis$$rtpa$$;
grant select on sys.v_$instance to cis$$rtpa$$;
grant select on sys.v_$obsolete_parameter to cis$$rtpa$$;
grant select on sys.v_$controlfile to cis$$rtpa$$;
grant select on sys.v_$logfile to cis$$rtpa$$;
grant select on sys.v_$log to cis$$rtpa$$;
grant select on sys.v_$RMAN_BACKUP_JOB_DETAILS to cis$$rtpa$$;
grant select on sys.v_$RMAN_BACKUP_JOB_DETAILS to cis$$rtpa$$;
grant select on sys.v_$TEMP_SPACE_HEADER to cis$$rtpa$$;
grant select on sys.v_$TEMP_EXTENT_POOL to cis$$rtpa$$;
grant select on sys.v_$osstat to cis$$rtpa$$;
grant select on sys.v_$system_parameter to cis$$rtpa$$;
grant select on sys.dba_registry_history to cis$$rtpa$$;
grant select on sys.dba_objects to cis$$rtpa$$;
grant select on sys.dba_segments to cis$$rtpa$$;
grant select on sys.dba_registry to cis$$rtpa$$;
grant select on sys.dba_role_privs to cis$$rtpa$$;
grant select on sys.dba_sys_privs to cis$$rtpa$$;
grant select on sys.DBA_DATA_FILES to cis$$rtpa$$;
grant select on sys.DBA_FREE_SPACE to cis$$rtpa$$;
grant select on sys.dba_registry_history to cis$$rtpa$$;

drop	synonym	cis$$rtpa$$.v$parameter;
drop	synonym	cis$$rtpa$$.v$database;
drop	synonym	cis$$rtpa$$.v$instance;
drop	synonym	cis$$rtpa$$.v$obsolete_parameter;
drop	synonym	cis$$rtpa$$.v$controlfile;
drop	synonym	cis$$rtpa$$.v$logfile;
drop	synonym	cis$$rtpa$$.v$log;
drop	synonym	cis$$rtpa$$.V$RMAN_BACKUP_JOB_DETAILS;
drop	synonym	cis$$rtpa$$.V$TEMP_SPACE_HEADER;
drop	synonym	cis$$rtpa$$.V$TEMP_EXTENT_POOL;
drop	synonym	cis$$rtpa$$.v$osstat;
drop	synonym	cis$$rtpa$$.v$system_parameter;
drop	synonym	cis$$rtpa$$.dba_registry_history;
drop	synonym	cis$$rtpa$$.dba_objects;
drop	synonym	cis$$rtpa$$.dba_segments;
drop	synonym	cis$$rtpa$$.dba_registry;
drop	synonym	cis$$rtpa$$.dba_role_privs;
drop	synonym	cis$$rtpa$$.dba_sys_privs;
drop	synonym	cis$$rtpa$$.DBA_DATA_FILES;
drop	synonym	cis$$rtpa$$.DBA_FREE_SPACE;
grant create any directory to cis$$rtpa$$;
create synonym cis$$rtpa$$.v$parameter for sys.v_$parameter ;
create synonym cis$$rtpa$$.v$database for sys.v_$database ;
create synonym cis$$rtpa$$.v$instance for sys.v_$instance ;
create synonym cis$$rtpa$$.v$obsolete_parameter for sys.v_$obsolete_parameter ;
create synonym cis$$rtpa$$.v$controlfile for sys.v_$controlfile ;
create synonym cis$$rtpa$$.v$logfile for sys.v_$logfile ;
create synonym cis$$rtpa$$.v$log for sys.v_$log ;
create synonym cis$$rtpa$$.V$RMAN_BACKUP_JOB_DETAILS for sys.v_$RMAN_BACKUP_JOB_DETAILS ;
rem create synonym V$RMAN_BACKUP_JOB_DETAILS for sys.v_$RMAN_BACKUP_JOB_DETAILS; 
create synonym cis$$rtpa$$.V$TEMP_SPACE_HEADER for sys.v_$TEMP_SPACE_HEADER ;
create synonym cis$$rtpa$$.V$TEMP_EXTENT_POOL for sys.v_$TEMP_EXTENT_POOL ;
create synonym cis$$rtpa$$.v$osstat for sys.v_$osstat ;
create synonym cis$$rtpa$$.v$system_parameter for sys.v_$system_parameter ;
create synonym cis$$rtpa$$.dba_registry_history for sys.dba_registry_history;
create synonym cis$$rtpa$$.dba_objects for sys.dba_objects;
create synonym cis$$rtpa$$.dba_segments for sys.dba_segments;
create synonym cis$$rtpa$$.dba_registry for sys.dba_registry;
create synonym cis$$rtpa$$.dba_role_privs for sys.dba_role_privs;
create synonym cis$$rtpa$$.dba_sys_privs for sys.dba_sys_privs;
create synonym cis$$rtpa$$.DBA_DATA_FILES for sys.DBA_DATA_FILES;
create synonym cis$$rtpa$$.DBA_FREE_SPACE for sys.DBA_FREE_SPACE;
